services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - 80:80
    volumes:
      - "./frontend:/app"
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
      - 8080:8090
    volumes:
      - "./backend:/app"
      